# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tasks_api import TasksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_task_by_id(self):
        """Test case for get_task_by_id

        Get a single task by id  # noqa: E501
        """
        pass

    def test_get_tasks(self):
        """Test case for get_tasks

        List tasks  # noqa: E501
        """
        pass

    def test_run(self):
        """Test case for run

        Run task  # noqa: E501
        """
        pass

    def test_stop(self):
        """Test case for stop

        Stop task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
