# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.security_management_anonymous_access_api import SecurityManagementAnonymousAccessApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSecurityManagementAnonymousAccessApi(unittest.TestCase):
    """SecurityManagementAnonymousAccessApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.security_management_anonymous_access_api.SecurityManagementAnonymousAccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read(self):
        """Test case for read

        Get Anonymous Access settings  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update Anonymous Access settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
