# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.blob_store_api import BlobStoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBlobStoreApi(unittest.TestCase):
    """BlobStoreApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.blob_store_api.BlobStoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_blob_store(self):
        """Test case for create_blob_store

        Create an S3 blob store  # noqa: E501
        """
        pass

    def test_create_file_blob_store(self):
        """Test case for create_file_blob_store

        Create a file blob store  # noqa: E501
        """
        pass

    def test_delete_blob_store(self):
        """Test case for delete_blob_store

        Delete a blob store by name  # noqa: E501
        """
        pass

    def test_get_blob_store(self):
        """Test case for get_blob_store

        Fetch a S3 blob store configuration  # noqa: E501
        """
        pass

    def test_get_file_blob_store_configuration(self):
        """Test case for get_file_blob_store_configuration

        Get a file blob store configuration by name  # noqa: E501
        """
        pass

    def test_list_blob_stores(self):
        """Test case for list_blob_stores

        List the blob stores  # noqa: E501
        """
        pass

    def test_quota_status(self):
        """Test case for quota_status

        Get quota status for a given blob store  # noqa: E501
        """
        pass

    def test_update_blob_store(self):
        """Test case for update_blob_store

        Update an S3 blob store configuration  # noqa: E501
        """
        pass

    def test_update_file_blob_store(self):
        """Test case for update_file_blob_store

        Update a file blob store configuration by name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
