# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_privilege_wildcard_request import ApiPrivilegeWildcardRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestApiPrivilegeWildcardRequest(unittest.TestCase):
    """ApiPrivilegeWildcardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiPrivilegeWildcardRequest(self):
        """Test ApiPrivilegeWildcardRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_privilege_wildcard_request.ApiPrivilegeWildcardRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
