# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.docker_group_repository_api_request import DockerGroupRepositoryApiRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestDockerGroupRepositoryApiRequest(unittest.TestCase):
    """DockerGroupRepositoryApiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDockerGroupRepositoryApiRequest(self):
        """Test DockerGroupRepositoryApiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.docker_group_repository_api_request.DockerGroupRepositoryApiRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
