# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lifecycle_api import LifecycleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLifecycleApi(unittest.TestCase):
    """LifecycleApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.lifecycle_api.LifecycleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bounce(self):
        """Test case for bounce

        Bounce lifecycle phase  # noqa: E501
        """
        pass

    def test_get_phase(self):
        """Test case for get_phase

        Get current lifecycle phase  # noqa: E501
        """
        pass

    def test_set_phase(self):
        """Test case for set_phase

        Move to new lifecycle phase  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
