# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.s3_blob_store_api_bucket_configuration import S3BlobStoreApiBucketConfiguration  # noqa: E501
from swagger_client.rest import ApiException


class TestS3BlobStoreApiBucketConfiguration(unittest.TestCase):
    """S3BlobStoreApiBucketConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3BlobStoreApiBucketConfiguration(self):
        """Test S3BlobStoreApiBucketConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.s3_blob_store_api_bucket_configuration.S3BlobStoreApiBucketConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
