# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_ldap_server_xo import UpdateLdapServerXo  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateLdapServerXo(unittest.TestCase):
    """UpdateLdapServerXo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateLdapServerXo(self):
        """Test UpdateLdapServerXo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_ldap_server_xo.UpdateLdapServerXo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
