# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_api import SearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search(self):
        """Test case for search

        Search components  # noqa: E501
        """
        pass

    def test_search_and_download_assets(self):
        """Test case for search_and_download_assets

        Search and download asset  # noqa: E501
        """
        pass

    def test_search_assets(self):
        """Test case for search_assets

        Search assets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
