# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cocoapods_proxy_repository_api_request import CocoapodsProxyRepositoryApiRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestCocoapodsProxyRepositoryApiRequest(unittest.TestCase):
    """CocoapodsProxyRepositoryApiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCocoapodsProxyRepositoryApiRequest(self):
        """Test CocoapodsProxyRepositoryApiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cocoapods_proxy_repository_api_request.CocoapodsProxyRepositoryApiRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
