# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.29.2-02
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class MavenAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version_policy': 'str',
        'layout_policy': 'str'
    }

    attribute_map = {
        'version_policy': 'versionPolicy',
        'layout_policy': 'layoutPolicy'
    }

    def __init__(self, version_policy=None, layout_policy=None, _configuration=None):  # noqa: E501
        """MavenAttributes - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._version_policy = None
        self._layout_policy = None
        self.discriminator = None

        if version_policy is not None:
            self.version_policy = version_policy
        if layout_policy is not None:
            self.layout_policy = layout_policy

    @property
    def version_policy(self):
        """Gets the version_policy of this MavenAttributes.  # noqa: E501

        What type of artifacts does this repository store?  # noqa: E501

        :return: The version_policy of this MavenAttributes.  # noqa: E501
        :rtype: str
        """
        return self._version_policy

    @version_policy.setter
    def version_policy(self, version_policy):
        """Sets the version_policy of this MavenAttributes.

        What type of artifacts does this repository store?  # noqa: E501

        :param version_policy: The version_policy of this MavenAttributes.  # noqa: E501
        :type: str
        """
        allowed_values = ["RELEASE", "SNAPSHOT", "MIXED"]  # noqa: E501
        if (self._configuration.client_side_validation and
                version_policy not in allowed_values):
            raise ValueError(
                "Invalid value for `version_policy` ({0}), must be one of {1}"  # noqa: E501
                .format(version_policy, allowed_values)
            )

        self._version_policy = version_policy

    @property
    def layout_policy(self):
        """Gets the layout_policy of this MavenAttributes.  # noqa: E501

        Validate that all paths are maven artifact or metadata paths  # noqa: E501

        :return: The layout_policy of this MavenAttributes.  # noqa: E501
        :rtype: str
        """
        return self._layout_policy

    @layout_policy.setter
    def layout_policy(self, layout_policy):
        """Sets the layout_policy of this MavenAttributes.

        Validate that all paths are maven artifact or metadata paths  # noqa: E501

        :param layout_policy: The layout_policy of this MavenAttributes.  # noqa: E501
        :type: str
        """
        allowed_values = ["STRICT", "PERMISSIVE"]  # noqa: E501
        if (self._configuration.client_side_validation and
                layout_policy not in allowed_values):
            raise ValueError(
                "Invalid value for `layout_policy` ({0}), must be one of {1}"  # noqa: E501
                .format(layout_policy, allowed_values)
            )

        self._layout_policy = layout_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MavenAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MavenAttributes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MavenAttributes):
            return True

        return self.to_dict() != other.to_dict()
